### ISSUE TITLE
IGNORECASE makes search fail

### ISSUE THREAD

**Issue by DamianEDiazF** [4A616Eh/CommScript#3]
If IGNORECASE is selected, no search (//example) will be executed.

**Comment by DamianEDiazF** [comment]
The following trace is shown in the console:

```
Traceback (most recent call last):
  File "...\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "...\commscr.py", line 1408, in recompile
    self.compiled = re.compile( e, self.getflags() )
  File "...\commscr.py", line 1388, in getflags
    flags = flags | var.get()
  File "...\Python37\lib\tkinter\__init__.py", line 510, in get
    return int(self._tk.getdouble(value))
_tkinter.TclError: expected floating-point number but got "RegexFlag.IGNORECASE"
```

**Comment by 4A616Eh** [comment]
Yes, I know...

**Comment by 4A616Eh** [comment]
Fixed.
